config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get 'change_status'
    end
  end

  resources :professionals

  resources :messages

  resources :services

  resources :customers

  resources :workers

  devise_for :users 

  root to: "welcome#bemvindo"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.name == ('admin')
    can :manage, :all
    elsif user.role.name == ('func')
    can :manage, :all
    elsif user.role.name == ('usuario')
    can :manage, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end

belongs_to :service
belongs_to :user
belongs_to :professional

end

app/models/customer.rb
class Customer < User
has_many :calendar


def self.search(search)
  if search
    where('nome LIKE ? and role_id = ?', "%#{search}%", "1")
  else
    all
  end
end


end

app/models/message.rb
class Message < ActiveRecord::Base

	
	
end

app/models/professional.rb
class Professional < ActiveRecord::Base

has_many :calendar


def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    all
  end
end

end

app/models/role.rb
class Role < ActiveRecord::Base
def change
t.string :name

has_many :user

end
end

app/models/service.rb
class Service < ActiveRecord::Base
has_many :calendar



def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :role
has_many :calendars
end

app/models/worker.rb
class Worker < User

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user
      if current_user.role_id == 1
        @calendars = current_user.calendars
      else
        @calendars = Calendar.search(params[:search])
      end
    end
    respond_with(@calendars)
  end

  def change_status
    @calendar = Calendar.find(params[:calendar])   
    @calendar.status = params[:new_status]
    @calendar.save
    redirect_to calendars_path
  end


  def show
    respond_with(@calendar)
  end

  def new
    @calendar = Calendar.new
    respond_with(@calendar)
  end

  def edit
  end

  def create
    @calendar = Calendar.new(calendar_params)
	  @calendar.date_send = Time.now
    @calendar.date_marked = Time.now
    @calendar.save
    respond_with(@calendar)
  end

  def update
    @calendar.update(calendar_params)
    respond_with(@calendar)
  end

  def destroy
    @calendar.destroy
    respond_with(@calendar)
  end

  private
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def calendar_params
      params.require(:calendar).permit(:hair_size, :hair_color, :date_request, :date_marked, :date_send, :observation, :status, :service_id, :professional_id, :user_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.save
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:name, :email, :description)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @services = Service.all
    @services = Service.search(params[:search]).order(created_at: :desc).paginate(:per_page => 2, :page => params[:page])
    respond_with(@services)


  end

  def show
    respond_with(@service)
  end

  def new
    @service = Service.new
    respond_with(@service)
  end

  def edit
  end

  def create
    @service = Service.new(service_params)
    @service.save
    flash[:notice] = 'Cadastro realizado com sucesso!'
    respond_with(@service) 
  end

  def update
    @service.update(service_params)
    respond_with(@service)
  end

  def destroy
    @service.destroy
    respond_with(@service)
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index

end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workers = Array.new
      Worker.search(params[:search]).each do |worker|
      if worker.role_id == 2
        @workers << worker
      end
      end

    respond_with(@workers)
  end

  def show
    respond_with(@worker)
  end

  def new
    @worker = Worker.new
    respond_with(@worker)
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)
    @worker.role_id = 2
    @worker.save
    flash[:notice] = 'Cadastro realizado com sucesso!'
    respond_with(@worker) 
  end

  def update
    @worker.update(worker_params)
    respond_with(@worker)
  end

  def destroy
    @worker.destroy
    respond_with(@worker)
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:email, :password, :nome, :endereco, :telcelular, :telfixo, :operadora_celular, :operadora_fixo, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/profissionais_helper.rb
module ProfissionaisHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendars/_form.html.erb
<%= simple_form_for(@calendar) do |f| %>
  <%= f.error_notification %>

  <div class="container-fluid">
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.association :user, label:'Cliente',label_method: :nome, value_method: :id, include_blank: false, collection: User.where(["role_id = ?","1"]), :input_html => {class: 'form-control', disabled: ''} %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :hair_color, label:'Cor do cabelo', :input_html => {class: 'form-control',  placeholder: 'Castanho escuro',  disabled: ''},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">  
                  <%= f.input :hair_size, label:'Tamanho do cabelo', collection: ["Curto", "Medio", "Comprido"], input_html: {class: 'form-control',  disabled: ''} %>
            </div>

            <div class="col-sm-6 col-xs-6">
                  <%= f.input :date_request, label:'Data Marcada', :as => :string, :input_html => {data: {behaviour: "datepicker"},:placeholder => 'Selecione...', class: 'form-control'} %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                  <%= f.association :service, label:'Serviço', label_method: :description, value_method: :id, include_blank: false, :input_html => {class: 'form-control', disabled: ''} %>
            </div>

            <div class="col-sm-6 col-xs-6">
                  <%= f.association :professional, label:'Profissional', label_method: :name, value_method: :id, include_blank: false, :input_html => {class: 'form-control'} %>  

            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-12 col-xs-12">
                <%= f.input :observation, label:'Observação', :input_html => {class: 'form-control', disabled: ''}%>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

          <%= f.input :status, input_html: {value: "Pre-agendado", type:"hidden"}, :as => :hidden %>


        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="form-actions" >
              <%= f.submit 'Pré-agendar', class: "form-actions btn btn-success btn-block" %>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(calendars_path, class: "form-actions btn btn-danger btn-block") do %>
                <div class="text-center" style="font-size:14px"> 
                   <i class="fa fa-ban"></i>
                        <span>Cancelar</span>
                </div>
              <% end %>
          </div>
        </div>   
  </div>
<% end %>

 <script type="text/javascript">
  $('[data-behaviour~=datepicker]').datepicker({
    dateFormat: "dd/mm/yy",
    "weekStart": 1,
    autoclose: true,
    language: "pt-BR"
  });
</script>

app/views/calendars/edit.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="#">Agendamentos</a></li>
			<li><a href="#">Pré-Agendar Solicitação</a></li>
		</ol>
	</div>
</div>
<h4 class="page-header">Pré-Agendar Solicitação</h4>

<%= render 'form' %>

<!--

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

-->

app/views/calendars/show.html.erb
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Home</a></li>
      <li><a href="#">Agendamentos</a></li>
    </ol>
  </div>
</div>
<h4 class="page-header">Solicitação nº <%= @calendar.id %></h4>
<% if current_user %>
<% if current_user.role_id == 1 %>

<div class="container-fluid">
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                  <strong>Cliente:</strong>
                    <%= @calendar.user_id %>
            </div>

            <div class="col-sm-6 col-xs-6">
                   <strong>Status:</strong>
                    <%= @calendar.status %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                    <strong>Data de Envio:</strong>
                      <%= @calendar.date_send %>
            </div>

            <div class="col-sm-6 col-xs-6">
                    <strong>Date Solicitada:</strong>
                       <%= @calendar.date_request %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                  <strong>Tamanho do Cabelo:</strong>
                    <%= @calendar.hair_size %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <strong>Cor do Cabelo:</strong>
                    <%= @calendar.hair_color %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <strong>Profissional:</strong>
                  <%= @calendar.professional_id %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <strong>Serviço:</strong>
                   <%= @calendar.service_id %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 col-xs-12">
                <strong>Observação:</strong>
                   <%= @calendar.observation %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
</div>

<div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= link_to(edit_calendar_path(@calendar), class: "form-actions btn btn-warning btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-edit"></i>
                          <span>Editar</span>
                  </div>
            <% end %>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(calendars_path, class: "form-actions btn btn-danger btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-mail-reply"></i>
                          <span>Voltar</span>
                  </div>
                <% end %>
          </div>
        </div>

<% else %>

<div class="container-fluid">
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                  <strong>Cliente:</strong>
                    <%= @calendar.user_id %>
            </div>

            <div class="col-sm-6 col-xs-6">
                   <strong>Status:</strong>
                    <%= @calendar.status %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                    <strong>Data de Envio:</strong>
                      <%= @calendar.date_send %>
            </div>

            <div class="col-sm-6 col-xs-6">
                    <strong>Date Solicitada:</strong>
                       <%= @calendar.date_request %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                  <strong>Tamanho do Cabelo:</strong>
                    <%= @calendar.hair_size %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <strong>Cor do Cabelo:</strong>
                    <%= @calendar.hair_color %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <strong>Profissional:</strong>
                  <%= @calendar.professional_id %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <strong>Serviço:</strong>
                   <%= @calendar.service_id %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
        <div class="row show-grid">
            <div class="col-sm-12 col-xs-12">
                <strong>Observação:</strong>
                   <%= @calendar.observation %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
</div>
       
        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= link_to(edit_calendar_path(@calendar), class: "form-actions btn btn-warning btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-edit"></i>
                          <span>Editar</span>
                  </div>
            <% end %>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(calendars_path, class: "form-actions btn btn-danger btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-mail-reply"></i>
                          <span>Voltar</span>
                  </div>
                <% end %>
          </div>
        </div>


<% end %>
<% end %>

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= message.email %></td>
        <td><%= message.description %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @message.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @message.description %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>

    <div class="container-fluid">
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.input :description, label:'Serviço', :input_html => {class: 'form-control',  placeholder: 'Corte'},  autofocus: true %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :price, label:'Preço',:input_html => {class: 'form-control',  placeholder: 'R$20.00'},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>



        <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="form-actions" >
              <%= f.submit 'Confirmar', class: "form-actions btn btn-success btn-block" %>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(services_path, class: "form-actions btn btn-danger btn-block") do %>
                <div class="text-center" style="font-size:14px"> 
                   <i class="fa fa-ban"></i>
                        <span>Cancelar</span>
                </div>
              <% end %>
          </div>
        </div>


<% end %>

app/views/services/edit.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="#">Cadastro - Serviços</a></li>
		</ol>
	</div>
</div>
<h4 class="page-header">Edição</h4>

<%= render 'form' %>

app/views/services/index.html.erb
<!--
<h1>Listing services</h1>

<%= form_tag services_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.description %></td>
        <td><%= service.price %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @services %>

<br>

<%= link_to 'New Service', new_service_path %>
-->
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Home</a></li>
      <li><a href="#">Cadastros - Serviços</a></li>
    </ol>
  </div>
</div>
<h4 class="page-header">Serviços</h4>


<div class="row-fluid">
  
  <div id="dashboard_tabs" class="col-xs-12 col-sm-12">
    <!--Start Dashboard Tab 1-->
    <div id="dashboard-overview" class="row" style="visibility: visible; position: relative;">
      <div id="ow-marketplace" class="col-sm-12 col-md-12">
        <h4 class="page-header">

          <%= link_to(new_service_path, class: "btn btn-info btn-sm") do %>
                <div class="text-left" style="font-size:15px"> 
                         <i style="font-size:22px" class="fa fa-file-o"></i>
                             <span>Novo Serviço</span>
                      </div>
              <% end %>

        </h4>
        
        <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-shopping-cart"></i>
          <span>Lista de Serviços</span>
        </div>
        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding">
        <%= form_tag services_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Buscar", :name => nil %>
          </p>
        <% end %>
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-1">
          <thead>
            <tr>
              <th>Descrição</th>
              <th>Preço</th>
              <th align="center">Ações</th>
            </tr>
          </thead>
          <tbody>
          <!-- Start: list_row -->
            <% @services.each do |service| %>
              <tr>
                <td><%= service.description %></td>
                <td><%= service.price %></td>
                <td align="center">
                <%= link_to(service, class: "btn btn-defaut btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-eye"></i>
                             <span></span>
                      </div>
                <% end %>
                <%= link_to(edit_service_path(service), class: "btn btn-warning btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-edit"></i>
                             <span></span>
                      </div>
               <% end %>
               <%= link_to(service, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-times-circle-o"></i>
                             <span></span>
                      </div>
               <% end %>



                </td>
              </tr>
            <% end %>
          <!-- End: list_row -->
          </tbody>
          <tfoot>
            <tr>
              <th>Descrição</th>
              <th>Preço</th>
              <th align="center">Ações</th>
            </tr>
          </tfoot>
        </table>
        <%= will_paginate @services %>
      </div>
    </div>
        
        
        
      </div>
    </div>
    <!--End Dashboard Tab 1-->
    <!--Start Dashboard Tab 2-->
    
    <!--Start Dashboard Tab 3-->
    
    <!--End Dashboard Tab 3-->
    <!--Start Dashboard Tab 4-->
    
    <!--End Dashboard Tab 4-->
  </div>
  <div class="clearfix"></div>
</div>
<!--End Dashboard 2 -->
<div style="height: 40px;"></div>

<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  TestTable1();
  TestTable2();
  TestTable3();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
});
</script>

app/views/services/new.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="#">Cadastro - Serviços</a></li>
		</ol>
	</div>
</div>
<h4 class="page-header">Novo Serviço</h4>

<%= render 'form' %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

	<div class="row">
	  <div id="breadcrumb" class="col-md-12">
	    <ol class="breadcrumb">
	      <li><a href="#">Home</a></li>
	      <li><a href="#">Agendamentos</a></li>
	    </ol>
	  </div>
	</div>
	<h4 class="page-header">Visualizar Serviço</h4>

	<div class="container-fluid">
	        <div align="center" class="row show-grid">
	            <div class="col-sm-6 col-xs-6">
					  <strong>Descrição:</strong>
					  <%= @service.description %>
				</div>

				<div class="col-sm-6 col-xs-6">
					   <strong>Preço:</strong>
  							R$<%= @service.price %>
				</div>
			</div>
	</div>		

<br>

		<div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= link_to(edit_service_path(@service), class: "form-actions btn btn-warning btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-edit"></i>
                          <span>Editar</span>
                  </div>
            <% end %>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(services_path, class: "form-actions btn btn-danger btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-mail-reply"></i>
                          <span>Voltar</span>
                  </div>
                <% end %>
          </div>
        </div>

          <div class="clearfix visible-xs"></div>