config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get 'change_status'
    end
  end

  resources :professionals

  resources :messages

  resources :services

  resources :customers

  resources :workers

  devise_for :users 

  root to: "welcome#bemvindo"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.name == ('admin')
    can :manage, :all
    elsif user.role.name == ('func')
    can :manage, :all
    elsif user.role.name == ('usuario')
    can :manage, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end

belongs_to :service
belongs_to :user
belongs_to :professional

end

app/models/customer.rb
class Customer < User
has_many :calendar


def self.search(search)
  if search
    where('nome LIKE ? and role_id = ?', "%#{search}%", "1")
  else
    all
  end
end


end

app/models/message.rb
class Message < ActiveRecord::Base

	
	
end

app/models/professional.rb
class Professional < ActiveRecord::Base

has_many :calendar


def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    all
  end
end

end

app/models/role.rb
class Role < ActiveRecord::Base
def change
t.string :name

has_many :user

end
end

app/models/service.rb
class Service < ActiveRecord::Base
has_many :calendar



def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :role
has_many :calendars
end

app/models/worker.rb
class Worker < User

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.save
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:name, :email, :description)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @services = Service.all
    @services = Service.search(params[:search]).order(created_at: :desc).paginate(:per_page => 2, :page => params[:page])
    respond_with(@services)


  end

  def show
    respond_with(@service)
  end

  def new
    @service = Service.new
    respond_with(@service)
  end

  def edit
  end

  def create
    @service = Service.new(service_params)
    @service.save
    flash[:notice] = 'Cadastro realizado com sucesso!'
    respond_with(@service) 
  end

  def update
    @service.update(service_params)
    respond_with(@service)
  end

  def destroy
    @service.destroy
    respond_with(@service)
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index

end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workers = Array.new
      Worker.search(params[:search]).each do |worker|
      if worker.role_id == 2
        @workers << worker
      end
      end

    respond_with(@workers)
  end

  def show
    respond_with(@worker)
  end

  def new
    @worker = Worker.new
    respond_with(@worker)
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)
    @worker.role_id = 2
    @worker.save
    flash[:notice] = 'Cadastro realizado com sucesso!'
    respond_with(@worker) 
  end

  def update
    @worker.update(worker_params)
    respond_with(@worker)
  end

  def destroy
    @worker.destroy
    respond_with(@worker)
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:email, :password, :nome, :endereco, :telcelular, :telfixo, :operadora_celular, :operadora_fixo, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/profissionais_helper.rb
module ProfissionaisHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/bemvindo.html.erb
<% if current_user %>
	<% if current_user.role_id == 1 %>
		<div class="jumbotron text-center" style="margin-top:70px">
		    <h1>Bem Vindo ao Sistema de Agendamentos On-line!</h1>
		    <p class="lead">The Bootstrap 3 grid is fluid only. This example shows how to use a custom container to create a fixed width CLIENTE.</p><br>
		    <p><a class="btn btn-large btn-success" href="<%= new_user_session_path  %> "style="font-size:20px">Vamos começar!</a></p>
		</div>
	<% end %>
	<% if current_user.role_id == 2 %>
		<div class="jumbotron text-center" style="margin-top:70px">
		    <h1>Bem Vindo ao Sistema de Agendamentos On-line!</h1>
		    <p class="lead">The Bootstrap 3 grid is fluid only. This example shows how to use a custom container to create a fixed width FUNCIONARIO.</p><br>
		    <p><a class="btn btn-large btn-success" href="<%= new_user_session_path  %> "style="font-size:20px">Vamos começar!</a></p>
		</div>
	<% end %>
	<% if current_user.role_id == 3 %>
		<div class="jumbotron text-center" style="margin-top:70px">
		    <h1>Bem Vindo ao Sistema de Agendamentos On-line!</h1>
		    <p class="lead">The Bootstrap 3 grid is fluid only. This example shows how to use a custom container to create a fixed width ADMINISTRADOR.</p><br>
		    <p><a class="btn btn-large btn-success" href="<%= new_user_session_path  %> "style="font-size:20px">Vamos começar!</a></p>
		</div>
	<% end %>
<% else %>
	<div class="container">
		<div class="jumbotron text-center" style="margin-top:100px">
		    <h1>Bem Vindo ao Sistema de Agendamentos On-line!</h1>
		    <p class="lead">The Bootstrap 3 grid is fluid only. This example shows how to use a custom container to create a fixed width Visitante.</p><br>
		    <p><a class="btn btn-large btn-success" href="<%= new_user_session_path  %> "style="font-size:20px">Vamos começar!</a></p>
		</div>
	</div>	
<% end %>

app/views/welcome/index.html.erb
Qualquer coisa

app/views/workers/_form.html.erb
<%= simple_form_for(@worker) do |f| %>
  <%= f.error_notification %>

<div class="container-fluid">
        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.input :email, label:'E-mail', :input_html => {class: 'form-control',  placeholder: 'exemplo@mail.com'},  autofocus: true %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :password, label:'Senha',:input_html => {class: 'form-control', placeholder: 'Digite aqui!'},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.input :nome, label:'Nome', :input_html => {class: 'form-control',  placeholder: 'Ex: João Victor Belo'},  autofocus: true %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :endereco, label:'Endereço',:input_html => {class: 'form-control', placeholder: 'Ex: Av. Sul, n 200'},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.input :telcelular, label:'Celular', :input_html => {class: 'form-control',  placeholder: 'Ex: 11 91234-1233'},  autofocus: true %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :operadora_celular, label:'Operadora',:input_html => {class: 'form-control', placeholder: 'Ex: Vezion, TIM, VIVO'},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>

        <div class="row show-grid">
            <div class="col-sm-6 col-xs-6">
                <%= f.input :telfixo, label:'Telefone Fixo', :input_html => {class: 'form-control',  placeholder: 'Ex: 11 1234-1233'},  autofocus: true %>
            </div>

            <div class="col-sm-6 col-xs-6">
                <%= f.input :operadora_fixo, label:'Operadora',:input_html => {class: 'form-control', placeholder: 'Ex: Oi, TELEMAR, NET'},  autofocus: true %>
            </div>
            <div class="clearfix visible-xs"></div>
        </div>
</div>


         <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="form-actions" >
              <%= f.submit 'Confirmar', class: "form-actions btn btn-success btn-block" %>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(workers_path, class: "form-actions btn btn-danger btn-block") do %>
                <div class="text-center" style="font-size:14px"> 
                   <i class="fa fa-ban"></i>
                        <span>Cancelar</span>
                </div>
              <% end %>
          </div>
        </div>

<% end %>

app/views/workers/edit.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="#">Cadastros - Funcionários</a></li>
		</ol>
	</div>
</div>
<h4 class="page-header">Editar Cadastro</h4>
<%= render 'form' %>

app/views/workers/index.html.erb
<!--
<h1>Listing Workers</h1>

<%= form_tag workers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :nome => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>E-mail</th>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telcelular</th>
      <th>Telfixo</th>
      <th>Operadora_celular</th>
      <th>Operadora_fixo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.email %></td>
        <td><%= worker.nome %></td>
        <td><%= worker.endereco %></td>
        <td><%= worker.telcelular %></td>
        <td><%= worker.telfixo %></td>
        <td><%= worker.operadora_celular %></td>
        <td><%= worker.operadora_fixo %></td>                
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Novo Funcionário', new_worker_path %>
-->
<div class="row">
  <div id="breadcrumb" class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="#">Home</a></li>
      <li><a href="#">Cadastros - Funcionários</a></li>
    </ol>
  </div>
</div>
<h4 class="page-header">Funcionários</h4>


<div class="row-fluid">
  
  <div id="dashboard_tabs" class="col-xs-12 col-sm-12">
    <!--Start Dashboard Tab 1-->
    <div id="dashboard-overview" class="row" style="visibility: visible; position: relative;">
      <div id="ow-marketplace" class="col-sm-12 col-md-12">
        <h4 class="page-header">

          <%= link_to(new_worker_path, class: "btn btn-info btn-sm") do %>
                <div class="text-left" style="font-size:15px"> 
                         <i style="font-size:22px" class="fa fa-user"></i>
                             <span>Adicionar Funcionário</span>
                      </div>
              <% end %>

        </h4>
        
        <div class="box">
      <div class="box-header">
        <div class="box-name">
          <i class="fa fa-users"></i>
          <span>Lista de Funcionários</span>
        </div>
        <div class="no-move"></div>
      </div>
      <div class="box-content no-padding">
          <%= form_tag workers_path, :method => 'get' do %>
            <p>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :nome => nil %>
            </p>
          <% end %>
        <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-1">
          <thead>
            <tr>
              <th>E-mail</th>
              <th>Nome</th>
              <th>Celular</th>
              <th>Tel. Fixo</th>
              <th colspan="3">Ações</th>
            </tr>
          </thead>
          <tbody>
          <!-- Start: list_row -->
            <% @workers.each do |worker| %>
              <tr>
                <td><%= worker.email %></td>
                <td><%= worker.nome %></td>
                <td><%= worker.telcelular %></td>
                <td><%= worker.telfixo %></td> 
                <td align="center">
                <%= link_to(worker, class: "btn btn-defaut btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-eye"></i>
                             <span></span>
                      </div>
                <% end %>
                <%= link_to(edit_worker_path(worker), class: "btn btn-warning btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-edit"></i>
                             <span></span>
                      </div>
               <% end %>
               <%= link_to(worker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm") do%>
                      <div class="text-center" style="font-size:15px"> 
                         <i class="fa fa-times-circle-o"></i>
                             <span></span>
                      </div>
               <% end %>



                </td>
              </tr>
            <% end %>
          <!-- End: list_row -->
          </tbody>
        </table>
      </div>
    </div>
        
        
        
      </div>
    </div>
    <!--End Dashboard Tab 1-->
    <!--Start Dashboard Tab 2-->
    
    <!--Start Dashboard Tab 3-->
    
    <!--End Dashboard Tab 3-->
    <!--Start Dashboard Tab 4-->
    
    <!--End Dashboard Tab 4-->
  </div>
  <div class="clearfix"></div>
</div>
<!--End Dashboard 2 -->
<div style="height: 40px;"></div>
<script type="text/javascript">
// Run Datables plugin and create 3 variants of settings
function AllTables(){
  TestTable1();
  TestTable2();
  TestTable3();
  LoadSelect2Script(MakeSelect2);
}
function MakeSelect2(){
  $('select').select2();
  $('.dataTables_filter').each(function(){
    $(this).find('label input[type=text]').attr('placeholder', 'Search');
  });
}
$(document).ready(function() {
  // Load Datatables and run plugin on tables 
  LoadDataTablesScripts(AllTables);
  // Add Drag-n-Drop feature
  WinMove();
});
</script>

app/views/workers/new.html.erb
<div class="row">
	<div id="breadcrumb" class="col-md-12">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li><a href="#">Cadastros - Funcionários</a></li>
		</ol>
	</div>
</div>
<h4 class="page-header">Novo Cadastro</h4>

<%= render 'form' %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <div id="breadcrumb" class="col-md-12">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Cadastros - Funcinários</a></li>
      </ol>
    </div>
  </div>
  <h4 class="page-header">Visualizar Cadastro</h4>

  <div class="container-fluid">
        <div class="row show-grid">
          <div class="col-sm-6 col-xs-6">
                <strong>E-mail:</strong>
                  <%= @worker.email %>
          </div>

          <div class="col-sm-6 col-xs-6">
                <strong>Nome:</strong>
                   <%= @worker.nome %>
         </div>
        </div>


        <div class="row show-grid">
          <div class="col-sm-12 col-xs-12">
                <strong>Endereco:</strong>
                  <%= @worker.endereco %>
          </div>
        </div>

        <div align="center" class="row show-grid">
          <div class="col-sm-3 col-xs-3">
                <strong>Celular:</strong>
                  <%= @worker.telcelular %>
          </div>

          <div class="col-sm-3 col-xs-3">
                <strong>Operadora:</strong>
                  <%= @worker.operadora_celular %>
         </div>

         <div class="col-sm-3 col-xs-3">
                <strong>Fixo:</strong>
                  <%= @worker.telfixo %>
          </div>

          <div class="col-sm-3 col-xs-3">
                <strong>Operadora:</strong>
                  <%= @worker.operadora_fixo %>
         </div>
        </div>
  </div>    

<br>

       <div class="row">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= link_to(edit_worker_path(@worker), class: "form-actions btn btn-warning btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-edit"></i>
                          <span>Editar</span>
                  </div>
            <% end %>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
              <%= link_to(workers_path, class: "form-actions btn btn-danger btn-block") do %>
                  <div class="text-center" style="font-size:14px"> 
                     <i class="fa fa-mail-reply"></i>
                          <span>Voltar</span>
                  </div>
                <% end %>
          </div>
        </div>

          <div class="clearfix visible-xs"></div>