config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get 'change_status'
    end
  end

  resources :professionals

  resources :messages

  resources :services

  resources :customers

  resources :workers

  devise_for :users 

  root to: "welcome#bemvindo"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.name == ('admin')
    can :manage, :all
    elsif user.role.name == ('func')
    can :manage, :all
    elsif user.role.name == ('usuario')
    can :manage, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end

belongs_to :service
belongs_to :user
belongs_to :professional

end

app/models/customer.rb
class Customer < User
has_many :calendar


def self.search(search)
  if search
    where('nome LIKE ? and role_id = ?', "%#{search}%", "1")
  else
    all
  end
end


end

app/models/message.rb
class Message < ActiveRecord::Base

	
	
end

app/models/professional.rb
class Professional < ActiveRecord::Base

has_many :calendar


def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    all
  end
end

end

app/models/role.rb
class Role < ActiveRecord::Base
def change
t.string :name

has_many :user

end
end

app/models/service.rb
class Service < ActiveRecord::Base
has_many :calendar



def self.search(search)
  if search
    where('description LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :role
has_many :calendars
end

app/models/worker.rb
class Worker < User

def self.search(search)
  if search
    where('nome LIKE ?', "%#{search}%")
  else
    all
  end
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index

end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workers = Array.new
      Worker.search(params[:search]).each do |worker|
      if worker.role_id == 2
        @workers << worker
      end
      end

    respond_with(@workers)
  end

  def show
    respond_with(@worker)
  end

  def new
    @worker = Worker.new
    respond_with(@worker)
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)
    @worker.role_id = 2
    @worker.save
    flash[:notice] = 'Cadastro realizado com sucesso!'
    respond_with(@worker) 
  end

  def update
    @worker.update(worker_params)
    respond_with(@worker)
  end

  def destroy
    @worker.destroy
    respond_with(@worker)
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:email, :password, :nome, :endereco, :telcelular, :telfixo, :operadora_celular, :operadora_fixo, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/profissionais_helper.rb
module ProfissionaisHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html (cвpia).erb
<!DOCTYPE html>
<html>
<head>
  <title>Sisweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Registrar', new_user_registration_path %>
<%= link_to 'Entrar', new_user_session_path %>
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>



<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Folder</title>
  <meta name="description" content="description">
  <meta name="author" content="DevOOPS">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag "bootstrap.css" %>
  <%= stylesheet_link_tag "jquery-ui.min.css" %>
  <%= stylesheet_link_tag "fullcalendar.css" %>
  <%= stylesheet_link_tag "xcharts.min.css" %>
  <%= stylesheet_link_tag "select2.css" %>
  <%= stylesheet_link_tag "style.css" %>
  <%= stylesheet_link_tag "jquery.fancybox.css" %>
   <%= stylesheet_link_tag "jquery.datetimepicker.css" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="screensaver">
	<canvas id="canvas"></canvas>
	<i class="fa fa-lock" id="screen_unlock"></i>
</div>
<div id="modalbox">
	<div class="devoops-modal">
		<div class="devoops-modal-header">
			<div class="modal-header-name">
				<span>Basic table</span>
			</div>
			<div class="box-icons">
				<a class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="devoops-modal-inner">
		</div>
		<div class="devoops-modal-bottom">
		</div>
	</div>
</div>
<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-12 col-sm-2">
				<a href="<%= root_path %>">SISWEB</a>

			</div>
			<div id="top-panel" class="col-xs-12 col-sm-10">
				<div class="row">
					<div class="col-xs-8 col-sm-4">
						<a href="#" class="show-sidebar">
						  <i class="fa fa-bars"></i>
						</a>
						<div id="search">
							<input type="text" placeholder="search"/>
							<i class="fa fa-search"></i>
						</div>
					</div>
					<div class="col-xs-4 col-sm-8 top-panel-right">
						<ul class="nav navbar-nav pull-right panel-menu">
							<li class="hidden-xs">
								<a href="index.html" class="modal-link">
									<i class="fa fa-bell"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a class="ajax-link" href="ajax/calendar.html">
									<i class="fa fa-calendar"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a href="ajax/page_messages.html" class="ajax-link">
									<i class="fa fa-envelope"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
										<img src="avatar.jpg" class="img-rounded" alt="avatar" />
									</div>
									<i class="fa fa-angle-down pull-right"></i>
									<div class="user-mini pull-right">
										<span class="welcome">Bem vindo,</span>
										<% if current_user %>
										<span><%= current_user.nome %></span>
										<% else %>
										<span>Visitante!</span>
										<% end %>
									</div>
								</a>
								<ul class="dropdown-menu">
									<% if current_user %>
									<li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Profile</span>
										</a>
									</li>
									<li>
										<a href="ajax/page_messages.html" class="ajax-link">
											<i class="fa fa-envelope"></i>
											<span>Messages</span>
										</a>
									</li>
									<li>
										<a href="ajax/gallery_simple.html" class="ajax-link">
											<i class="fa fa-picture-o"></i>
											<span>Albums</span>
										</a>
									</li>
									<li>
										<a href="ajax/calendar.html" class="ajax-link">
											<i class="fa fa-tasks"></i>
											<span>Tasks</span>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>Settings</span>
										</a>
									</li>
									<li>
							<%= link_to(destroy_user_session_path, :method => :delete) do %>
											<i class="fa fa-power-off"></i>
											<span>Logout</span>
										<% end %>
									</li>
									<% else %>
									<li>
										<a href="<%= new_user_session_path  %>">
											<i class="fa fa-user"></i>
											<span>Entrar</span>
										</a>
									</li><li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Cadastrar-se</span>
										</a>
									</li>
									<% end %>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->

<div id="main" class="container-fluid">
	<div class="row">
			<div id="sidebar-left" class="col-xs-2 col-sm-2">
				<ul class="nav main-menu">
					<li>
						<a href="<%= calendars_path %>" class="">
							<i class="fa fa-book"></i>
							<span class="hidden-xs">Agendamentos</span>
						</a>
					</li>
			<% if current_user %>		
				<% if current_user.role_id != 1 %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-bar-chart-o"></i>
							<span class="hidden-xs">Cadastros</span>
						</a>
						<ul class="dropdown-menu">
							<% if current_user.role_id == 2 %>
								<li><a class="#" href="<%= customers_path %>">Clientes</a></li>
							<% end %>
							<% if current_user.role_id == 2 %>
								<li><a class="#" href="<%= workers_path %>">Funcionários</a></li>
								<li><a class="#" href="<%= services_path %>">Serviços</a></li>
								<li><a class="#" href="<%= professionals_path %>">Profissionais</a></li>
							<% end %>
			<% end %>
						</ul>
					</li>
				
					<!--
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-table"></i>
							 <span class="hidden-xs">Tables</span>
						</a>
						<ul class="dropdown-menu">
							<li><a class="ajax-link" href="ajax/tables_simple.html">Simple Tables</a></li>
							<li><a class="ajax-link" href="ajax/tables_datatables.html">Data Tables</a></li>
							<li><a class="ajax-link" href="ajax/tables_beauty.html">Beauty Tables</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-pencil-square-o"></i>
							 <span class="hidden-xs">Forms</span>
						</a>
						<ul class="dropdown-menu">
							<li><a class="ajax-link" href="ajax/forms_elements.html">Elements</a></li>
							<li><a class="ajax-link" href="ajax/forms_layouts.html">Layouts</a></li>
							<li><a class="ajax-link" href="ajax/forms_file_uploader.html">File Uploader</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-desktop"></i>
							 <span class="hidden-xs">UI Elements</span>
						</a>
						<ul class="dropdown-menu">
							<li><a class="ajax-link" href="ajax/ui_grid.html">Grid</a></li>
							<li><a class="ajax-link" href="ajax/ui_buttons.html">Buttons</a></li>
							<li><a class="ajax-link" href="ajax/ui_progressbars.html">Progress Bars</a></li>
							<li><a class="ajax-link" href="ajax/ui_jquery-ui.html">Jquery UI</a></li>
							<li><a class="ajax-link" href="ajax/ui_icons.html">Icons</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-list"></i>
							 <span class="hidden-xs">Pages</span>
						</a>
						<ul class="dropdown-menu">
							<li><a href="ajax/page_login.html">Login</a></li>
							<li><a href="ajax/page_register.html">Register</a></li>
							<li><a id="locked-screen" class="submenu" href="ajax/page_locked.html">Locked Screen</a></li>
							<li><a class="ajax-link" href="ajax/page_contacts.html">Contacts</a></li>
							<li><a class="ajax-link" href="ajax/page_feed.html">Feed</a></li>
							<li><a class="ajax-link add-full" href="ajax/page_messages.html">Messages</a></li>
							<li><a class="ajax-link" href="ajax/page_pricing.html">Pricing</a></li>
							<li><a class="ajax-link" href="ajax/page_invoice.html">Invoice</a></li>
							<li><a class="ajax-link" href="ajax/page_search.html">Search Results</a></li>
							<li><a class="ajax-link" href="ajax/page_404.html">Error 404</a></li>
							<li><a href="ajax/page_500.html">Error 500</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-map-marker"></i>
							<span class="hidden-xs">Maps</span>
						</a>
						<ul class="dropdown-menu">
							<li><a class="ajax-link" href="ajax/maps.html">OpenStreetMap</a></li>
							<li><a class="ajax-link" href="ajax/map_fullscreen.html">Fullscreen map</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-picture-o"></i>
							 <span class="hidden-xs">Gallery</span>
						</a>
						<ul class="dropdown-menu">
							<li><a class="ajax-link" href="ajax/gallery_simple.html">Simple Gallery</a></li>
							<li><a class="ajax-link" href="ajax/gallery_flickr.html">Flickr Gallery</a></li>
						</ul>
					</li>
					<li>
						 <a class="ajax-link" href="ajax/typography.html">
							 <i class="fa fa-font"></i>
							 <span class="hidden-xs">Typography</span>
						</a>
					</li>
					 <li>
						<a class="ajax-link" href="ajax/calendar.html">
							 <i class="fa fa-calendar"></i>
							 <span class="hidden-xs">Calendar</span>
						</a>
					 </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle">
							<i class="fa fa-picture-o"></i>
							 <span class="hidden-xs">Multilevel menu</span>
						</a>
						<ul class="dropdown-menu">
							<li><a href="#">First level menu</a></li>
							<li><a href="#">First level menu</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle">
									<i class="fa fa-plus-square"></i>
									<span class="hidden-xs">Second level menu group</span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#">Second level menu</a></li>
									<li><a href="#">Second level menu</a></li>
									<li class="dropdown">
										<a href="#" class="dropdown-toggle">
											<i class="fa fa-plus-square"></i>
											<span class="hidden-xs">Three level menu group</span>
										</a>
										<ul class="dropdown-menu">
											<li><a href="#">Three level menu</a></li>
											<li><a href="#">Three level menu</a></li>
											<li class="dropdown">
												<a href="#" class="dropdown-toggle">
													<i class="fa fa-plus-square"></i>
													<span class="hidden-xs">Four level menu group</span>
												</a>
												<ul class="dropdown-menu">
													<li><a href="#">Four level menu</a></li>
													<li><a href="#">Four level menu</a></li>
													<li class="dropdown">
														<a href="#" class="dropdown-toggle">
															<i class="fa fa-plus-square"></i>
															<span class="hidden-xs">Five level menu group</span>
														</a>
														<ul class="dropdown-menu">
															<li><a href="#">Five level menu</a></li>
															<li><a href="#">Five level menu</a></li>
															<li class="dropdown">
																<a href="#" class="dropdown-toggle">
																	<i class="fa fa-plus-square"></i>
																	<span class="hidden-xs">Six level menu group</span>
																</a>
																<ul class="dropdown-menu">
																	<li><a href="#">Six level menu</a></li>
																	<li><a href="#">Six level menu</a></li>
																</ul>
															</li>
														</ul>
													</li>
												</ul>
											</li>
											<li><a href="#">Three level menu</a></li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>
					</li>
				-->
				</ul>
			</div>
		
		<!--Start Content-->
		<div id="content" class="col-xs-12 col-sm-10">
			<div>
				<%= yield %>
			</div>
		</div>
<% else %>

<%= yield %>

<% end %>
		<!--End Content-->
	</div>
</div>

</body>
</html>